version: "3.9"
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000

  # db:
  #   container_name: postgres
  #   image: postgres
  #   expose:
  #     - 5433
  #   ports:
  #     - 5433:5433
  #   volumes:
  #     - data:/data/db
  #   environment:
  #     - POSTGRES_HOST
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_DATABASE}
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - PGPORT=5433
  #   command: -p 5433
  #   restart: always

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: proyekvix
  #   ports:
  #     - "5000:80"

volumes:
  data: {}
